---
- name: Ensure Nsight log directory exists
  file:
    path: "{{ nsight_exporter_log_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

# Additional tasks to parse and expose Nsight logs can be added here.
