slurm_exporter_version: "0.2.0"
slurm_exporter_download_url: "https://github.com/vpenso/slurm_exporter/releases/download/v{{ slurm_exporter_version }}/slurm_exporter-{{ slurm_exporter_version }}.linux-amd64.tar.gz"
slurm_exporter_install_dir: "/usr/local/bin"
slurm_exporter_port: 9779
