---
- name: Configure Rocky Linux Compute Nodes with Node Exporter
  hosts: compute_nodes
  become: yes
  roles:
    - node_exporter

- name: Configure GPU Nodes with Nvidia DCGM Exporter
  hosts: gpu_nodes
  become: yes
  roles:
    - nvidia_dcgm_exporter

- name: Configure SLURM Job Scheduler
  hosts: job_scheduler
  become: yes
  roles:
    - slurm_exporter

- name: Configure WEKA Environment Exporter
  hosts: storage_weka
  become: yes
  roles:
    - wekafs_exporter
